# Generated by Django 2.2.4 on 2021-03-05 07:08

from django.db import migrations, models
import django.db.models.deletion
import image_recognition.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='検証名')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.UUIDField(default='88f0e082d81041e5bb19fc83895868f2', editable=False, primary_key=True, serialize=False)),
                ('target', models.FileField(upload_to=image_recognition.models.target_upload_path, verbose_name='検証用ファイル')),
                ('result', models.FileField(default=None, upload_to=image_recognition.models.upload_path, verbose_name='検証結果')),
                ('json', models.FileField(default=None, upload_to=image_recognition.models.upload_path, verbose_name='レスポンスJSON')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='image_recognition.Type')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
